#!/bin/sh
set -e

# This script is called from the Dockerfile ENTRYPOINT and stored in the
# root of the resulting workspace container for reference.

if test -e /var/run/been_built; then
  exec sh -c "su - $(head -1 /var/run/defuser)"
fi

# ----------------------- get custom user info -----------------------

name="you"
echo -n "User Name ($name): "
read -r val
test -n "$val" && name="$val"

id="9001"
echo -n "User ID ($id): "
read -r val
test -n "$val" && id="$val"

group="9001"
echo -n "User Group ($group): "
read -r val
test -n "$val" && group="$val"

home="/home/you"
echo -n "User Home Directory ($home): "
read -r val
test -n "$val" && home="$home"

shell="/bin/bash"
echo -n "User Shell ($shell): "
read -r val
test -n "$val" && shell="$val"

# ---------------- attempt to install different shell ----------------

shell_name=${shell##*/}
if ! type "$shell_name"; then
  echo Attempting to install shell: $shell_name
  apt install -y "$shell_name"
fi

# ------------------------ create a super user -----------------------

groupadd -g "$group" "$name"
useradd -m -s "$shell" -d "$home" -u "$id" -g "$group" "$name"
echo "$name ALL=(ALL:ALL) NOPASSWD:ALL" >>/etc/sudoers
chown -R "$name:$group" "$home"

# -------------------- cache build and exec shell --------------------

touch /var/run/been_built
echo "$name" >/var/run/defuser
exec /bin/sh -c "su - $name"
